- defaults:
    link:
        relink: true
        create: true
        force: true
        glob: true        
    shell:
        stdout: true
        stderr: true

- create:
    - $HOME/.config

- clean:
    $HOME:
        force: true
    $HOME/.config:
        recursive: true

