- defaults:
    link:
        relink: true
        create: true
        force: true
        glob: true        
    shell:
        stdout: true
        stderr: true
    brewfile:
        stdout: true,
    brew:
        auto_bootstrap: true
        stderr: False,
        stdout: False,        

- create:
    - $HOME/.config

- clean:
    $HOME:
        force: true
    $HOME/.config:
        recursive: true

